name: DigitalMazeiOS
options:
  minimumXcodeGenVersion: 2.38.0
settings:
  base:
    SWIFT_VERSION: 5.0
    PRODUCT_BUNDLE_IDENTIFIER: com.example.digitalmazeios
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
targets:
  DigitalMazeiOS:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Sources
    resources:
      - path: www
        type: folder
    settings:
      base:
        INFOPLIST_KEY_CFBundleDisplayName: Digital Maze
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UIRequiredDeviceCapabilities:
          - arm64
        INFOPLIST_KEY_UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        INFOPLIST_KEY_NSLocalNetworkUsageDescription: Local network access is optional for testing.
        INFOPLIST_KEY_NSMotionUsageDescription: Used to tilt the maze board with device motion.
    scheme:
      testTargets: []
